#! /bin/sh

sxhkd &
$HOME/.config/polybar/launch.sh
#bspc monitor -d I II III IV V VI VII VIII IX X

bspc monitor HDMI-0 -d I II III IV V 
bspc monitor HDMI-1 -d VI VII VIII IX X 



bspc config border_width         2
bspc config window_gap          30

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop=^4 state=fullscreen
bspc rule -a Alacritty desktop=^1 
bspc rule -a Nemo desktop=^1 
bspc rule -a Chromium desktop=^6 state=fullscreen
bspc rule -a Brave-browser desktop=^6 state=fullscreen
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Virt-manager desktop=^2 state=fullscreen
bspc rule -a libreoffice-writer follow=on focus=on desktop=^6 state=fullscreen
